version: '3.3'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '8080:8080'

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

