spring:
  application:
    name: homework
  datasource:
    url: jdbc:postgresql://localhost:5432/fields_awardees_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: 'classpath:db.migration/changeLog.xml'
    enabled: true
server:
  port: 8081
  servlet:
    context-path: /homework
  error:
    include-exception: true
    include-message: always
application:
  cash:
    enabled: "true"
  type:
    calculator: "iterative"


